# Generated by Django 6.0.6 on 2026-06-29 17:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('news', '新闻'), ('trivia', '趣闻轶事'), ('official_works', '官方作品')], db_index=True, max_length=32, verbose_name='所属页面')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='链接标识')),
                ('summary', models.TextField(max_length=300, verbose_name='摘要')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('cover_image', models.FileField(blank=True, help_text='支持 jpg、png、webp、gif。', upload_to='news/covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='封面图片')),
                ('source_name', models.CharField(blank=True, max_length=80, verbose_name='来源名称')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发布时间')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='发布到前台')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻条目',
                'verbose_name_plural': '新闻条目',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
