# Generated by Django 6.0.6 on 2026-06-29 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submission', '投稿'), ('feedback', '反馈建议')], default='submission', max_length=20, verbose_name='类型')),
                ('target_section', models.CharField(choices=[('news', '新闻'), ('trivia', '趣闻轶事'), ('official_works', '官方作品')], default='news', max_length=32, verbose_name='目标页面')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('author_name', models.CharField(blank=True, max_length=80, verbose_name='投稿人称呼')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='联系方式')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='摘要/简述')),
                ('body', models.TextField(verbose_name='正文/反馈内容')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('attachment', models.FileField(blank=True, help_text='支持 jpg、png、webp、gif。', upload_to='submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='附件图片')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '润色中'), ('published', '已发布'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='审核状态')),
                ('editor_title', models.CharField(blank=True, max_length=120, verbose_name='润色后标题')),
                ('editor_summary', models.TextField(blank=True, max_length=300, verbose_name='润色后摘要')),
                ('editor_body', models.TextField(blank=True, verbose_name='润色后正文')),
                ('editor_notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='articles.article', verbose_name='发布后的新闻条目')),
            ],
            options={
                'verbose_name': '投稿与反馈',
                'verbose_name_plural': '投稿与反馈',
                'ordering': ('-created_at',),
            },
        ),
    ]
