# Generated by Django 6.0.6 on 2026-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_format',
            field=models.CharField(choices=[('text', '纯文本'), ('markdown', 'Markdown'), ('html', 'HTML')], default='text', help_text='列表页只显示摘要，详情页按此格式显示完整正文。', max_length=20, verbose_name='正文格式'),
        ),
    ]
